server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
    session:
      timeout: 60

spring:
  application:
    name: "bookSpring"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookSpring?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

#p6spy
decorator:
  datasource:
    p6spy:
      enable-logging: true

host:
  name: "http://localhost:3000"

jwt:
  secret: ${JWT_SECRET}